{"id": 31651, "game_modes": [{"id": 1, "name": "Single player"}], "involved_companies": [{"id": 48470, "company": {"id": 2245, "name": "Big Fish Games"}, "developer": false}], "name": "Grave Mania: Pandemic Pandemonium", "platforms": [6], "release_dates": [{"id": 75012, "date": 1472515200, "platform": 6, "y": 2016}], "screenshots": [{"id": 49321, "url": "//images.igdb.com/igdb/image/upload/t_thumb/ykptorenskowri1h14s2.jpg"}, {"id": 49322, "url": "//images.igdb.com/igdb/image/upload/t_thumb/uymtewnazumq6fg8oqsb.jpg"}, {"id": 49323, "url": "//images.igdb.com/igdb/image/upload/t_thumb/fhq427pnssldse3ktz1q.jpg"}, {"id": 49324, "url": "//images.igdb.com/igdb/image/upload/t_thumb/webc1lqketrakgsbzlgw.jpg"}, {"id": 49325, "url": "//images.igdb.com/igdb/image/upload/t_thumb/lnu3v6ha4e3k8cl6356t.jpg"}], "summary": "The Locas are back!"}